name: Newspaper

on:
  # Every day at 4:00 am, Beijing time (20:00 UTC)
  schedule:
    - cron: '0 20 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - development
          - production
        default: 'development'

jobs:
  newspaper:
    uses: ./.github/workflows/_base.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment || 'production' }}
      timeout-minutes: 60
      command: newspaper exec
